server:
  port: 8050
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defauleZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true